spring:
  application:
    name: Film Catalog Application
  datasource:
    url: jdbc:postgresql://localhost:5432/spase_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
